### ISSUE TITLE
Incorrect foot mapping

### ISSUE THREAD

**Issue by c-hospodar** [tqosu/FLEX#1]
<img width="2326" alt="Screenshot 2023-11-27 at 4 57 40 PM" src="https://github.com/tqosu/FLEX/assets/78567140/58964261-5cb7-4ffe-a628-0f8c81b644ed">

This is an issue where no matter how I try to relabel the steps, the output is incorrect. 

S44 slope trial 23

**Comment by tqosu** [comment]
I cannot reproduce this. Do you want to have a quick meeting to show this?

**Comment by tqosu** [comment]
![Fig1](https://github.com/tqosu/FLEX/assets/91351064/4bbf66d1-30b2-4fa4-bb55-adb7b7ad0a3b)

**Comment by tqosu** [comment]
Restart the program.
