### ISSUE TITLE
S60 trial 49 cannot add foot in correct location

### ISSUE THREAD

**Issue by c-hospodar** [tqosu/FLEX#13]
<img width="2560" alt="Screenshot 2023-12-04 at 2 28 04 PM" src="https://github.com/tqosu/FLEX/assets/78567140/8400c07e-35f9-433e-aa06-4cfb2ae916e8">

I have deleted box detections from view 2, but the bottom visualization does not update the location of the foot, and it's not possible for me to add a foot in the correct location. npy file in google drive

[2023-12-04_13-42-42_app_log.txt](https://github.com/tqosu/FLEX/files/13550521/2023-12-04_13-42-42_app_log.txt)

**Comment by tqosu** [comment]
Currently, you need to select this trial again (reopen this trial) to address it.

**Comment by c-hospodar** [comment]
Is this something that can be addressed in future updates of the code? It
really disrupts correction to have to continually exit and reopen the same
trial.

On Mon, Dec 4, 2023 at 2:55 PM tqosu ***@***.***> wrote:

> Currently, you need to select this trial again (reopen this trial) to
> address it.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tqosu_FLEX_issues_13-23issuecomment-2D1839375731&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=Mo6iIdrfbBV344KTGsXUmox9EeYZmnrvJgbryVGZ9zU&m=vHMsfECVL6rGZYLUXRu1tRJfpc2uoHdiCDzEj4ysOLB1VkPbJUJJje1dJ-jn-8hm&s=fp_1S0zibyPzscKrAmPHgUD-xcNvi2cTCtxripr7iUU&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ASXNNZC53GXKOBWWPA5OBO3YHYTC3AVCNFSM6AAAAABAGQBPICVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMZZGM3TKNZTGE&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=Mo6iIdrfbBV344KTGsXUmox9EeYZmnrvJgbryVGZ9zU&m=vHMsfECVL6rGZYLUXRu1tRJfpc2uoHdiCDzEj4ysOLB1VkPbJUJJje1dJ-jn-8hm&s=qJW7G1RWG1ZMX4dEAj-EzpUN9zMigcu22d6HjS9rKog&e=>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>


-- 
*Christina Hospodar, MS*
Ph.D. Student | NYU Infant Action Lab <http://www.psych.nyu.edu/adolph/>
Department of Psychology
Pronouns: she/her/hers

**Comment by tqosu** [comment]
I believe most of the issues you mentioned were related to the undo operation. The latest version should address them all. Please update your code and create these issues again if they still exist.
