### ISSUE TITLE
Observation about issues with removing views

### ISSUE THREAD

**Issue by c-hospodar** [tqosu/FLEX#14]
It seems that there is some limit to the amount of times you can remove and add a view. If I click it back and forth to see how it changes the step visualization, at some point it seems to stop adjusting anything and/or will not show the deletion of the box in the video. Might be playing a role in how it will happen for me but you can't seem to replicate the issue.

**Comment by tqosu** [comment]
Thanks. I agree.

**Comment by c-hospodar** [comment]
It also seems to not work properly if you've inserted a step and then used
command-z to remove it (and then try to remove a view and re-add the step).

On Mon, Dec 4, 2023 at 3:27 PM tqosu ***@***.***> wrote:

> Closed #14
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tqosu_FLEX_issues_14&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=Mo6iIdrfbBV344KTGsXUmox9EeYZmnrvJgbryVGZ9zU&m=RbyiIDFe3lPBrGx-YHzzdl6ZA4xN6B_qqFPq4pwLEfu_6oWKdXvBRI36LUVwZYZ2&s=FNk6c8q2XmbDdeVuN0gTgDZI5A8pwUOBnfzeANaIQG4&e=>
> as completed.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tqosu_FLEX_issues_14-23event-2D11144033914&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=Mo6iIdrfbBV344KTGsXUmox9EeYZmnrvJgbryVGZ9zU&m=RbyiIDFe3lPBrGx-YHzzdl6ZA4xN6B_qqFPq4pwLEfu_6oWKdXvBRI36LUVwZYZ2&s=2gua2K5_mmP-Kf4U-3G4mL2rL_TeoxdpU_t4F7oEDZ0&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ASXNNZF2HWM3X4FYKLWQZYLYHYWZNAVCNFSM6AAAAABAGQ5RL6VHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJRGE2DIMBTGM4TCNA&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=Mo6iIdrfbBV344KTGsXUmox9EeYZmnrvJgbryVGZ9zU&m=RbyiIDFe3lPBrGx-YHzzdl6ZA4xN6B_qqFPq4pwLEfu_6oWKdXvBRI36LUVwZYZ2&s=-znLtFBUZE_gpsItp6-ZzpXDqkX8-wRvKjIeoHD4gd8&e=>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>


-- 
*Christina Hospodar, MS*
Ph.D. Student | NYU Infant Action Lab <http://www.psych.nyu.edu/adolph/>
Department of Psychology
Pronouns: she/her/hers
