### ISSUE TITLE
add shortcut for clear steps?

### ISSUE THREAD

**Issue by c-hospodar** [tqosu/FLEX#16]
Can you add a shortcut to clear all steps to the clear button on the numpad? Thanks!

**Comment by c-hospodar** [comment]
I would rather not do key_2. It is too close to other keys we use very often, and I wouldn't want to accidentally clear our work. Why can't it be added to the "clear" button on the numpad?

**Comment by c-hospodar** [comment]
What about "="?

On Wed, Dec 6, 2023 at 7:06 PM tqosu ***@***.***> wrote:

> I do not have that key on my keyboard.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tqosu_FLEX_issues_16-23issuecomment-2D1843906229&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=Mo6iIdrfbBV344KTGsXUmox9EeYZmnrvJgbryVGZ9zU&m=PjqzRmjP5MGl5NghXfizy91chb8SDF9ha7A0TPc6CrNlVsu3lbx1SFq_0pqFbequ&s=A-JoCdlj4X2BqvFhwA4VZeh-YxuGJirNDVaOOvWjNbI&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ASXNNZAZQDO235Z54EZMK5DYIECBLAVCNFSM6AAAAABAKELUC2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNBTHEYDMMRSHE&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=Mo6iIdrfbBV344KTGsXUmox9EeYZmnrvJgbryVGZ9zU&m=PjqzRmjP5MGl5NghXfizy91chb8SDF9ha7A0TPc6CrNlVsu3lbx1SFq_0pqFbequ&s=hndTPBCjOPgqCe7eP188U09YJwVOXN6NPiBWKcf6sKg&e=>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>


-- 
*Christina Hospodar, MS*
Ph.D. Student | NYU Infant Action Lab <http://www.psych.nyu.edu/adolph/>
Department of Psychology
Pronouns: she/her/hers

**Comment by c-hospodar** [comment]
Or let me know what other keys are options! But 2 will not work

**Comment by tqosu** [comment]
You can use 'Key_Equal'. Please update your code.
