### ISSUE TITLE
Boxes do not delete S60 trial 15

### ISSUE THREAD

**Issue by c-hospodar** [tqosu/FLEX#2]
[](https://drive.google.com/file/d/1aE7UpmtXU9x01h4y8mnJfOwmraCUCq6O/view?usp=drive_link)

I have had a few trials now where deleting the box detections does nothing (they do not appear to delete, and nothing happens to the detections in the visualization), so it's still not possible to add a step in the correct spot.

**Comment by tqosu** [comment]
Can you also share the log file in Google Drive?

**Comment by c-hospodar** [comment]
I did!

On Fri, Dec 1, 2023 at 3:16 PM tqosu ***@***.***> wrote:

> Can you also share the log file in Google Drive?
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tqosu_FLEX_issues_2-23issuecomment-2D1836720948&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=Mo6iIdrfbBV344KTGsXUmox9EeYZmnrvJgbryVGZ9zU&m=xCB_OtN9LRTMh5auvQESiFlpHer3QEvrDAV6YEDTTt3_izw1g_621US6M2GL0L4T&s=IkKRqX83Y04kBmqwhbRsuw5DAZs2aW16j5vIEsvM8D4&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ASXNNZCKUL4MXOBHIM7LPLTYHI3IDAVCNFSM6AAAAABADK5TCSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMZWG4ZDAOJUHA&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=Mo6iIdrfbBV344KTGsXUmox9EeYZmnrvJgbryVGZ9zU&m=xCB_OtN9LRTMh5auvQESiFlpHer3QEvrDAV6YEDTTt3_izw1g_621US6M2GL0L4T&s=7uKWcJC526OEu-H65StI3l8IvtfpD5OTQAs7sApS78Q&e=>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>


-- 
*Christina Hospodar, MS*
Ph.D. Student | NYU Infant Action Lab <http://www.psych.nyu.edu/adolph/>
Department of Psychology
Pronouns: she/her/hers

**Comment by tqosu** [comment]
I didn't see it. I mean the log in the LOG_ folder.

**Comment by tqosu** [comment]
Let's only keep the last issue related to this.

**Comment by tqosu** [comment]
Restarting the trial would be enough to address the issue.
