### ISSUE TITLE
s60 trial 59 video glitch

### ISSUE THREAD

**Issue by c-hospodar** [tqosu/FLEX#7]
<img width="2525" alt="Screenshot 2023-12-01 at 6 25 30 PM" src="https://github.com/tqosu/FLEX/assets/78567140/4c241dea-cc8a-4967-b6c9-3352725c7882">

video glitches and jumps from frame 79012 to 79013

**Comment by tqosu** [comment]
If you reopen it, it will not have this issue.

**Comment by tqosu** [comment]
related to #13
