### ISSUE TITLE
Program crashed

### ISSUE THREAD

**Issue by c-hospodar** [tqosu/FLEX#8]
I uploaded the latest LOG files to the google drive folder. I was correcting S60 and it crashed while I was trying to delete steps. It was the first trial I was in after updating the code.

**Comment by tqosu** [comment]
Yes. The most recent log after the crash will be the related one.

**Comment by tqosu** [comment]
Do you have any prompts for the crash? What's the error message?

**Comment by c-hospodar** [comment]
*2023-12-04 13:31:52,287 DEBUG    FlexUI.app playfront1 51456*

*2023-12-04 13:31:52,473 DEBUG    FlexUI.app playfront1 51457*

*2023-12-04 13:31:52,613 DEBUG    FlexUI.app playfront1 51458*

*2023-12-04 13:31:52,753 DEBUG    FlexUI.app playfront1 51459*

*2023-12-04 13:31:52,887 DEBUG    FlexUI.app playfront1 51460*

*2023-12-04 13:31:53,006 DEBUG    FlexUI.app playfront1 51461*

*2023-12-04 13:31:53,507 DEBUG    FlexUI.app playfront1 51462*

*2023-12-04 13:31:53,685 DEBUG    FlexUI.app playfront1 51463*

*2023-12-04 13:31:53,854 DEBUG    FlexUI.app playfront1 51464*

*2023-12-04 13:31:54,011 DEBUG    FlexUI.app playfront1 51465*

*2023-12-04 13:31:54,188 DEBUG    FlexUI.app playfront1 51466*

*2023-12-04 13:31:54,357 DEBUG    FlexUI.app playfront1 51467*

*2023-12-04 13:31:54,514 DEBUG    FlexUI.app playfront1 51468*

*2023-12-04 13:31:54,692 DEBUG    FlexUI.app playfront1 51469*

*2023-12-04 13:31:54,860 DEBUG    FlexUI.app playfront1 51470*

*2023-12-04 13:31:55,018 DEBUG    FlexUI.app playfront1 51471*

*2023-12-04 13:31:55,195 DEBUG    FlexUI.app playfront1 51472*

*2023-12-04 13:31:55,362 DEBUG    FlexUI.app playfront1 51473*

*2023-12-04 13:31:56,167 DEBUG    FlexUI.app playfront1 51474*

*2023-12-04 13:31:57,168 DEBUG    FlexUI.app playfront1 51475*

*2023-12-04 13:31:57,326 DEBUG    FlexUI.app playfront1 51476*

*2023-12-04 13:31:57,480 DEBUG    FlexUI.app playfront1 51477*

*2023-12-04 13:31:57,982 DEBUG    FlexUI.app playfront1 51478*

*2023-12-04 13:31:58,139 DEBUG    FlexUI.app playfront1 51479*

*2023-12-04 13:31:58,308 DEBUG    FlexUI.app playfront1 51480*

*2023-12-04 13:31:58,486 DEBUG    FlexUI.app playfront1 51481*

*2023-12-04 13:31:59,398 DEBUG    FlexUI.app PrevAction 51482*

*2023-12-04 13:31:59,839 DEBUG    FlexUI.app RemoveAction 51479*

*2023-12-04 13:31:59,911 DEBUG    FlexUI.app slope angle: 0*

*2023-12-04 13:32:00,696 DEBUG    FlexUI.app playfront1 51479*

*2023-12-04 13:32:00,895 DEBUG    FlexUI.app playfront1 51480*

*2023-12-04 13:32:01,038 DEBUG    FlexUI.app playfront1 51481*

*2023-12-04 13:32:01,168 DEBUG    FlexUI.app playfront1 51482*

*2023-12-04 13:32:01,318 DEBUG    FlexUI.app playfront1 51483*

*2023-12-04 13:32:02,377 DEBUG    FlexUI.app RemoveAction 51484*

*2023-12-04 13:32:02,450 DEBUG    FlexUI.app slope angle: 0*

*2023-12-04 13:32:03,056 DEBUG    FlexUI.app playfront1 51484*

*2023-12-04 13:32:03,206 DEBUG    FlexUI.app playfront1 51485*

*2023-12-04 13:32:05,334 DEBUG    FlexUI.app playfront1 51486*

*2023-12-04 13:32:05,487 DEBUG    FlexUI.app playfront1 51487*

*2023-12-04 13:32:05,623 DEBUG    FlexUI.app playfront1 51488*

*2023-12-04 13:32:05,792 DEBUG    FlexUI.app playfront1 51489*

*2023-12-04 13:32:05,968 DEBUG    FlexUI.app playfront1 51490*

*2023-12-04 13:32:05,993 DEBUG    FlexUI.app SaveAction 51491*

*2023-12-04 13:32:06,022 DEBUG    FlexUI.app
User/Christina/2021_Flex1_S60_Slope_MCH.csv 1*

*2023-12-04 13:32:06,201 DEBUG    FlexUI.app playfront1 51491*

Traceback (most recent call last):

  File "/Users/motoruser/Desktop/FLEX-main/FlexUI/app.py", line 948, in
setPosition

    self.main3Dviewer.setPosition(position)

  File
"/Users/motoruser/Desktop/FLEX-main/FlexUI/ViewerVideo/ResultWidgetApp.py",
line 373, in setPosition

    overlay = self.img.copy()

AttributeError: 'ResultApp' object has no attribute 'img'

Abort trap: 6

(myenv) kalab08m:FLEX-main motoruser$ python 1.py

On Mon, Dec 4, 2023 at 1:48 PM tqosu ***@***.***> wrote:

> Do you have any prompts for the crash? What's the error message?
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tqosu_FLEX_issues_8-23issuecomment-2D1839262785&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=Mo6iIdrfbBV344KTGsXUmox9EeYZmnrvJgbryVGZ9zU&m=arYQamZK29zZfaWyakMHYWEZxymL1PE_zcXRfJpst67en4UHyWn2jHncPedQA6b1&s=LzmBWlKV0HuuTl1ZmwqqqzArb2UkiszlfLu63BzBPtw&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ASXNNZCYBPJT6XP4FLZ2GH3YHYLIBAVCNFSM6AAAAABAGN3JRCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMZZGI3DENZYGU&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=Mo6iIdrfbBV344KTGsXUmox9EeYZmnrvJgbryVGZ9zU&m=arYQamZK29zZfaWyakMHYWEZxymL1PE_zcXRfJpst67en4UHyWn2jHncPedQA6b1&s=dxjnBMS3IStC4tl6slENamSzskYKhJcEq9wZ5XE9O7U&e=>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>


-- 
*Christina Hospodar, MS*
Ph.D. Student | NYU Infant Action Lab <http://www.psych.nyu.edu/adolph/>
Department of Psychology
Pronouns: she/her/hers

**Comment by tqosu** [comment]
related to #15
